# Generated by Django 5.1.3 on 2024-12-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_organizer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attender',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
