# Generated by Django 5.1.3 on 2024-12-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='organizer_username',
            new_name='organizer_name',
        ),
    ]
